name = input("Enter your name: " )
age = int(input("How old are you? "))
country = input("what country do you reside? ")
experirence = int(input("How many years of experience do you have? "))
language = input("what is your favourite programming language? ")
current_language = bool(input("are you currently learning python? "))

print("===============================")
print("DEVELOPER PROFILE")
print("===============================")
print(f"Name: {name}") 
print(f"Age: {age}")
print(f"Country: {country}")
print(f"Programming Experience: {experirence} years")
print(f"Favorite Language: {language}")
print(f"Currently Learning Python: {current_language}")